---

- name: Checking FTDv Failover state
  gather_facts: no
  hosts: FMC
  connection: local

  vars:
    FMC_IP: 192.168.255.220
    FTDv1: 86929a22-543d-11ec-a4c0-e26057195b3c
    FTDv2: 89e07bd6-543d-11ec-9aa4-df09791ea19a
    jmesquery: 'metadata.primaryStatus'

  tasks:

  - name: Authenticate with FMCv
    include_role:
      name:  auth    

  - debug: 
      msg: |
              {{ token.x_auth_access_token }}

  - name: get token
    set_fact:
      acc_token: "{{token.x_auth_access_token}}"
      domain_uuid: "{{token.domain_uuid}}"

  - name: Get Device HA pairs 
    include_role:
      name:  HAPairs
    
  - debug:
      msg: |
              {{ devicepairs }}
  - name: get JSON structure           
    set_fact:
      devicepairs_json: "{{ devicepairs.json }}"      

  - debug:
      msg: |    
              {{devicepairs_json}}

  - name: get METADATA structure           
    set_fact:
      devicepairs_meta: "{{devicepairs_json | json_query('items[].metadata')}}"      
  - name: get FTD-HA name 
    set_fact:
      devicepairs_name: "{{devicepairs.json | json_query('items[].name')}}"      
  - name: get Primary  Status
    set_fact:
      PStatus: "{{ devicepairs_meta[0].primaryStatus.currentStatus }}"     

  - name: get Secondary Status
    set_fact:
      SStatus: "{{ devicepairs_meta[0].secondaryStatus.currentStatus }}"     

  - debug:
      msg: |    
              {{SStatus}}
  - debug:
      msg: |
              " DeviceHA: {{devicepairs_name}} Primary Status is {{PStatus}} , Secondary Status is {{SStatus}}"
               
