---

- name: Checking FTDv Failover state
  gather_facts: no
  hosts: FMC
  connection: local

  vars:
    FMC_IP: 192.168.255.220
    slack_token: TL48R5E3D/B02PYCBTXB4/uoKsOeQGCks2WsQ4FeHmORGI
  environment:
    http_proxy: http://proxy.esl.cisco.com:8080
    https_proxy: http://proxy.esl.cisco.com:8080
    no_proxy: 192.168.255.220

  tasks:

  - name: Authenticate with FMCv
    include_role:
      name:  auth    

  - debug: 
      msg: |
              {{ token.x_auth_access_token }}

  - name: get token
    set_fact:
      acc_token: "{{token.x_auth_access_token}}"
      domain_uuid: "{{token.domain_uuid}}"

  - name: Get Device HA pairs 
    include_role:
      name:  HAPairs

  - name: Touch previous.log
    ansible.builtin.file:
      path: previous.log
      state: touch
      mode: u=rw,g=rw,o=rw
    
# - name: Touch Previous state file 
#   shell:  touch previous.log
#   delegate_to:  localhost

  - name: Remove current g
    ansible.builtin.file:
      path: current.log
      state: absent

  - name: Touch previous.log
    ansible.builtin.file:
      path: current.log
      state: touch
      mode: u=rw,g=rw,o=rw
########### LOOP ##########
  - name: Loop inside JSON-Items
    lineinfile:
      path: current.log
      line: "HA Pair: '{{item.name}}' Primary FTD Status: {{item.metadata.primaryStatus.currentStatus}} , Secondary FTD Status: {{item.metadata.secondaryStatus.currentStatus}}"
    with_items: "{{ devicepairs.json | json_query('items[]') }}"     

  - name: DIFF STATES
    shell: diff current.log previous.log 
    delegate_to:  localhost               
    register: to_slack
    failed_when: "to_slack.rc > 1"

  - name: SLACK           
    slack:
     token: "{{ slack_token }}"
     msg: "{{to_slack.stdout}}" 
    delegate_to:  localhost               
    when: to_slack.rc!=0

  - name: Copying current state to previous state for next run
    shell:  cp current.log previous.log
    delegate_to:  localhost               
    run_once: true
