---

- name: Checking FTDv Failover state
  gather_facts: no
  hosts: FMC
  connection: local

  vars:
    FMC_IP: 192.168.255.220
    FTDv1: 86929a22-543d-11ec-a4c0-e26057195b3c
    FTDv2: 89e07bd6-543d-11ec-9aa4-df09791ea19a
    slack_token: TL48R5E3D/B02PYCBTXB4/uoKsOeQGCks2WsQ4FeHmORGI

  tasks:

  - name: Authenticate with FMCv
    include_role:
      name:  auth    

  - debug: 
      msg: |
              {{ token.x_auth_access_token }}

  - name: get token
    set_fact:
      acc_token: "{{token.x_auth_access_token}}"
      domain_uuid: "{{token.domain_uuid}}"

  - name: Get Device HA pairs 
    include_role:
      name:  HAPairs
    
  - name: Touch Previous state file 
    shell:  touch previous.log
    delegate_to:  localhost

  - name: Removing current state           
    shell:  rm current.log
    delegate_to:  localhost               

  - name: Touch current state file 
    shell:  touch current.log
    delegate_to:  localhost
########### LOOP ##########
  - name: Loop inside JSON-Items
    lineinfile:
      path: current.log
      line: "HA Pair: '{{item.name}}' Primary FTD Status: {{item.metadata.primaryStatus.currentStatus}} , Secondary FTD Status: {{item.metadata.secondaryStatus.currentStatus}}"
    with_items: "{{ devicepairs.json | json_query('items[]') }}"     

  - name: DIFF STATES
    shell: diff current.log previous.log 
    delegate_to:  localhost               
    register: to_slack
    failed_when: "to_slack.rc > 1"

  - name: SLACK           
    slack:
     token: "{{ slack_token }}"
     msg: "{{to_slack.stdout}}" 
    delegate_to:  localhost               
    when: to_slack.rc!=0

  - name: Copying current state to previous state for next run
    shell:  cp current.log previous.log
    delegate_to:  localhost               
    run_once: true
